### ISSUE TITLE
CI Implementation and Heroku Pipeline

### ISSUE THREAD

**Issue by BrennanAyers** [BrennanAyers/tsdbcg#12]
### UPDATE:
Travis needs a database setup, and needs to know it is using Postgres.
====
Setting up a Heroku Pipeline will allow our project to flourish and be testing in a Production environment consistently as we add features and functionality. 
For BE this looks like a Staging environment where we can hit endpoints with real live variables, and then pushing to Production after passing our QA stage.
For FE this looks like: 
Additionally, Travis CI or another CI tool will be another barrier to ensuring our code is functional alongside our tests.

**Comment by DavisC0801** [comment]
Confirmed TravisCI is working as intended and Heroku pipeline is deploying to staging environment.
