### ISSUE TITLE
Implement Deck Order mechanic

### ISSUE THREAD

**Issue by BrennanAyers** [BrennanAyers/tsdbcg#35]
To maintain parity between the Frontend and the Backend with a Players GameCards, we will need to implement logic to send and receive the order of a given Players deck of GameCards.
The flow for this looks like:
- GET Player State endpoint contains an array of GameCard objects in the order they should be drawn
- Frontend draws cards in this determined order for players
- Frontend sends POST at end of turn dictating which cards are discarded (and in what order)
- Backend finds new cards/existing cards to mark as Discarded

### Edge Cases
- Frontend shuffles Discard into Deck, Frontend sends us an updated Deck Order during the End Turn phase
- We update GameCard `deck_order` number to reflect this change

**Comment by DavisC0801** [comment]
Confirmed that order is randomly set on a created game.
