### ISSUE TITLE
New Game Endpoint

### ISSUE THREAD

**Issue by BrennanAyers** [BrennanAyers/tsdbcg#44]
```
As a user
I should be able to POST to the Games endpoint with my 
- Name
And start a new Game
And receive a body containing:
- My Player Name
- Player ID
- Game ID
```
Request:
`POST /api/v1/games`
`BODY: {player_name: "Ted"}`
Response
`BODY: {player_name: "Ted", player_id: 1, game_id: 1}`
-
On the backend, we will need to first create a new Game object, and then the new Player object attached to that Game. The Game will not start yet, as it does not have all required players.

**Comment by DavisC0801** [comment]
Incorrect inputs - Empty body and missing game id - returns an empty response and a 400 status code.
