### ISSUE TITLE
Player Join Endpoint

### ISSUE THREAD

**Issue by BrennanAyers** [BrennanAyers/tsdbcg#45]
```
As a user
I should be able to POST request 'api/v1/join_game'
With a Body containing my Player Name, and the Game ID
Of the Game I would like to join
And I will receive a response with a 200 status code, the Player Name, Player ID, and the Game ID
And a successful message of Game Started
```
Request:
`POST /api/v1/join_game`
`BODY: {player_name: "George", game_id: 1}`
Response:
`BODY: {player_name: "George", player_id: 2, game_id: 1, game_status: "Game Started"}`
-
Game Started implies that all required players have joined this game, and the backend has run the `Game.start` method, building out decks and cards for the frontend to render to each Player.

**Comment by DavisC0801** [comment]
Confirmed, see #72
