### ISSUE TITLE
Update Player State endpoint to follow Card Serialization conventions

### ISSUE THREAD

**Issue by BrennanAyers** [BrennanAyers/tsdbcg#54]
After confirming with the Frontend what Serialized Card objects should look like for the Game State, the same update needs to be applied to the Player State endpoint as well.
The final serialized Card Object should look like this:
```
{
      name: "Copper",
      category: "Money",
      cost: 0,
      victoryPoints: 0,
      spendingPower: 1,
      buyingPower: 0,
      actionsProvided: 0,
      cardsToDraw: 0,
      image: "copper.jpg",
      desc: "",
      tags: []
    }
```

**Comment by DavisC0801** [comment]
Confirmed response is in proper format on production query.
