### ISSUE TITLE
Add `rack-cors` to Project to facilitate Frontend making API calls

### ISSUE THREAD

**Issue by BrennanAyers** [BrennanAyers/tsdbcg#66]
We need to add the `rack-cors` gem to our project to allow the Frontend to both:
- Request to localhost
- Request to Heroku
We'll need to make sure we restrict our origins to `localhost:3001`, and whatever URL the Frontend chooses for their UI.

**Comment by DavisC0801** [comment]
Followup Issue opened to change whitelisting from *.*.
