### ISSUE TITLE
Add `default: 0` to Card attributes regarding points/actions

### ISSUE THREAD

**Issue by BrennanAyers** [BrennanAyers/tsdbcg#79]
Currently, the Integer fields on the Card objects do not have a default value. This will cause issues when Frontend is trying to render cards, as they are expecting 0's in the following attributes if they do not have that value, instead of `null`:
- Victory Points
- Spending Power
- Buying Power
- Actions Provided
- Cards to Draw

We will need to update the migrations and schema for these attributes on Card.

**Comment by DavisC0801** [comment]
Tested in QA by running Card.create(name: "test", category:"test", cost:0, image:"test", desc:"test", tags:"test"). Card was created successfully with 0 values, as expected.
